name: Code-coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: dockerx
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: build
        name: Build dev docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: codiumai/pr-agent:test
          cache-from: type=gha,scope=dev
          cache-to: type=gha,mode=max,scope=dev
          target: test

      - id: code_cov
        name: Test dev docker
        run: |
          docker run --rm codiumai/pr-agent:test pytest tests/unittest --cov=pr_agent

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: code-coverage
          fail_ci_if_error: true
        
          
